Post.delete_all  
Subject.delete_all


Subject.create(title: "John Bennett (Australian footballer)")  
Subject.create(title: "John Bennett (Australian politician)")  
Subject.create(title: "John Bennett (Canadian politician)")  
Subject.create(title: "John Bennett (Derbyshire cricketer)")  
Subject.create(title: "John Bennett (Hampshire cricketer)")  
Subject.create(title: "John Bennett (Irish politician)")  
Subject.create(title: "John Bennett (MP)")  
Subject.create(title: "John Bennett (Serjeant at Law)")  
Subject.create(title: "John Bennett (Victorian politician)")  
Subject.create(title: "John Bennett (actor)")  
Subject.create(title: "John Bennett (athlete)")  
Subject.create(title: "John Bennett (athletics)")  
Subject.create(title: "John Bennett (author)")  
Subject.create(title: "Middle range theory")  
Subject.create(title: "Middle range theory (archeology)")  
Subject.create(title: "Middle range theory (sociology)")  
Subject.create(title: "Middle rectal")  
Subject.create(title: "Middle rectal artery")  
Subject.create(title: "Middle rectal plexus")  
Subject.create(title: "Middle rectal vein")  
Subject.create(title: "Middle rectal veins")  
Subject.create(title: "Middle relief")  
Subject.create(title: "Middle relief pitcher")  
Subject.create(title: "Middle reliever")  
Subject.create(title: "Middle rhine highlands") 
Subject.create(title: "Middle river")  
Subject.create(title: "Middle sacral")  
Subject.create(title: "Middle sacral artery")  
Subject.create(title: "Middle sacral crest")  
Subject.create(title: "Middle sacral veins")  
Subject.create(title: "Middle saranac lake")  
Subject.create(title: "Middle scalene")  
Subject.create(title: "Middle school")  
Subject.create(title: "Middle school (China)")  
Subject.create(title: "Middle school of the kennebunks")  
Subject.create(title: "Middle school student (United States)")  
Subject.create(title: "Middle schools")  
Subject.create(title: "Middle schools in Arlington, Virginia")  
Subject.create(title: "Middle schools in England")  
Subject.create(title: "Middle schools in San Diego, California")  
Subject.create(title: "Middle schools in san diego")  
Subject.create(title: "Middle schools in san diego, ca")  
Subject.create(title: "Middle shogi")  
Subject.create(title: "Middle social class")  
Subject.create(title: "Middle solar system")  
Subject.create(title: "Middle spaces")  
Subject.create(title: "Middle spotted woodpecker")  
Subject.create(title: "Middle square")  
Subject.create(title: "Middle square method")  
Subject.create(title: "Middle state")  
Subject.create(title: "Middle states association of colleges and schools")  
Subject.create(title: "Middle stone age")  
Subject.create(title: "Middle stump")  
Subject.create(title: "Middle style")  
Subject.create(title: "Middle subscapular nerve")  
Subject.create(title: "Middle superior alveolar branch")  
Subject.create(title: "Middle superior alveolar nerve")  
Subject.create(title: "Middle suprarenal")  
Subject.create(title: "Middle suprarenal arteries")  
Subject.create(title: "Middle suprarenal artery")  
Subject.create(title: "Middle temporal area 21")  
Subject.create(title: "Middle temporal artery")  
Subject.create(title: "Middle temporal gyrus")  
Subject.create(title: "Middle term")  
Subject.create(title: "Middle thyrohyoid ligament")  
Subject.create(title: "Middle thyroid")  
Subject.create(title: "Middle thyroid vein")  
Subject.create(title: "Middle thyroid veins")  
Subject.create(title: "Middle tibiofibular ligament")  
Subject.create(title: "Middle tier")  
Subject.create(title: "Middle toe")  
Subject.create(title: "Middle turbinate")  
Subject.create(title: "Middle umbilical fold")  
Subject.create(title: "Middle umbilical ligament")  
Subject.create(title: "Middle vesical artery")  
Subject.create(title: "Middle voice")  
Subject.create(title: "Middle watch")  
Subject.create(title: "Middle way")  
Subject.create(title: "Middle welsh")  
Subject.create(title: "Middle welsh language")  
Subject.create(title: "Middle years of Rabindranath Tagore")  
Subject.create(title: "Middle Čakavian")  
Subject.create(title: "Middleage")  
Subject.create(title: "Middleaged")  
Subject.create(title: "Middleagedness")  
Subject.create(title: "Middlearth")  
Subject.create(title: "Middlebere Plateway")  
Subject.create(title: "Middlebere Tramway")  
Subject.create(title: "Middleberg")  
Subject.create(title: "Middleberg, Oklahoma")  
Subject.create(title: "Middlebie")  
Subject.create(title: "Middleboot Knotts")  
Subject.create(title: "Middleboro")  
Subject.create(title: "Middleboro, Indiana")  
Subject.create(title: "Middleboro, MA")  
Subject.create(title: "Middleboro, Massachusetts") 
Subject.create(title: "Middleboro, Nova Scotia")  
Subject.create(title: "Middleboro, Pennsylvania")  
Subject.create(title: "Middleboro Center, Massachusetts")  
Subject.create(title: "Middleboro Gazette")  
Subject.create(title: "Middleboro Railroad")  
Subject.create(title: "Middleboro Secondary")  
Subject.create(title: "Middleboro Subdivision")  
Subject.create(title: "Middleborough")  
Subject.create(title: "Middleborough, MA")  
Subject.create(title: "Middleborough, Ma")  
Subject.create(title: "Middleborough, Mass")  
Subject.create(title: "Middleborough, Massachusetts")  
Subject.create(title: "Middleborough/Lakeville")  
Subject.create(title: "Middleborough/Lakeville (MBTA station)")  
Subject.create(title: "Middleborough/Lakeville Line")  
Subject.create(title: "Middleborough (CC&HR station)")  
Subject.create(title: "Middleborough (MA)")  
Subject.create(title: "Middleborough Center")  
Subject.create(title: "Middleborough Center, MA")  
Subject.create(title: "Middleborough Center, Massachusetts")  
Subject.create(title: "Middleborough Center Historic District")  
Subject.create(title: "Middleborough High School")  
Subject.create(title: "Middleborough Public Library (Massachusetts)")  
Subject.create(title: "Middleborough Railroad")  
Subject.create(title: "Middleborough Rd")  
Subject.create(title: "Middleborough Waterworks")  
Subject.create(title: "Middleborough and Taunton Railroad")  
Subject.create(title: "Middlebourne")  
Subject.create(title: "Middlebourne, WV")  
Subject.create(title: "Middlebourne, West Virginia")  
Subject.create(title: "Middlebourne Historic District")  
Subject.create(title: "Middlebox")  
Subject.create(title: "Middlebranch, Ohio")  
Subject.create(title: "Middlebridge Scimitar")  
Subject.create(title: "Middlebrook")  
Subject.create(title: "Middlebrook, Greater Manchester")  
Subject.create(title: "Middlebrook, New Jersey")  
Subject.create(title: "Middlebrook, Virginia")  
Subject.create(title: "Middlebrook (Knoxville, Tennessee)")  
Subject.create(title: "Middlebrook (surname)")  
Subject.create(title: "Middlebrook 7H10 Agar")  
Subject.create(title: "Middlebrook 7H11 Agar")  
Subject.create(title: "Middlebrook 7H9 Broth")  
Subject.create(title: "Middlebrook Baronets")  
Subject.create(title: "Middlebrook Building")  
Subject.create(title: "Middlebrook Historic District")  
Subject.create(title: "Middlebrook Islands")  
Subject.create(title: "Middlebrook Middle School")  
Subject.create(title: "Middlebrook Pike")  
Subject.create(title: "Middlebrook Schools")  
Subject.create(title: "Middlebrook baronets")  
Subject.create(title: "Middlebrook encampment")  
Subject.create(title: "Middlebrooks")  
Subject.create(title: "Middlebrow")  
Subject.create(title: "Middleburg")  
Subject.create(title: "Middleburg, FL")  
Subject.create(title: "Middleburg, Florida")  
Subject.create(title: "Middleburg, Iowa")  
Subject.create(title: "Middleburg, Kentucky")  
Subject.create(title: "Middleburg, Logan County, Ohio")  
Subject.create(title: "Middleburg, Maryland")  
Subject.create(title: "Middleburg, NC")  
Subject.create(title: "Middleburg, North Carolina")  
Subject.create(title: "Middleburg, Ohio")  
Subject.create(title: "Middleburg, PA")  
Subject.create(title: "Middleburg, Pennsylvania")  
Subject.create(title: "Pin",description: "pedia") 